#%RAML 1.0 NamedExample

value:
  -
    ID: 101
    Name: Ironman
    Universe: MCU
    Ability: Superhuman
    Team: Avengers
    Movies: 3
  -
    ID: 102
    Name: Superman
    Universe: DCEU
    Ability: Superhuman
    Team: Justice League
    Movies: 2
  -
    ID: 103
    Name: Hawkeye
    Universe: MCU
    Ability: Human
    Team: Avengers
    Movies: 1
  -
    ID: 104
    Name: Batman
    Universe: DCEU
    Ability: Human
    Team: Justice League
    Movies: 3
  -
    ID: 105
    Name: Spiderman
    Universe: MCU
    Ability: Superhuman
    Team: Avengers
    Movies: 8    